// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Product struct {
	ID       *string  `json:"id"`
	Title    *string  `json:"title"`
	Price    *float64 `json:"price"`
	Discount *float64 `json:"discount"`
	Content  *string  `json:"content"`
	Avator   *string  `json:"avator"`
}

type ProductInput struct {
	Title    *string  `json:"title"`
	Price    *float64 `json:"price"`
	Discount *float64 `json:"discount"`
	Content  *string  `json:"content"`
	Avator   *string  `json:"avator"`
}
